version: "3.2"

services:
  web:
    build: ./images/php71
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
  db:
    image: percona
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - 3306:3306
volumes:
  my-datavolume: